config/routes.rb
Rails.application.routes.draw do
  # HTTP_VERB '/path', to: 'controller#action', as: :nickname
  # get '/', to: 'pages#home', as: :root
  root to: 'pages#home'
  get '/about', to: 'pages#about', as: :about
  get '/contact', to: 'pages#contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    # render about.html.erb
  end

  def contact
    # raise
    @members = ['sasha', 'sylvain', 'yann', 'doug', 'trouni']
    # @members = Member.all
    if params[:member]
      @members = @members.select do |member|
        member.start_with?(params[:member])
      end
    end
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>This is our Navbar</nav>
    <%# All of our views will be inserted here: %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>er + tab (dont show)</p>
<% Time.now %>
<p>pe + tab (show)</p>
<%=  %>
<p>cmd + ? -> ERB Comment</p>
<%#=  %>
<p><%= p @members %></p>

app/views/pages/contact.html.erb
<div class="container">
  <h1>Contact</h1>
  <%# Form has action => PATH and method => HTTP_VERB %>
  <%# Filter/Search the le wagon members %>
  <h4>Get Form</h4>
  <form action="/contact" method="get">
    <label for="member">Member</label>
    <%# input needs a type and a name %>
    <%# The name is the key in our params %>
    <input type="text" name="member" value='<%= params[:member] %>'>
    <button type='submit' class="btn btn-primary">Search</button>
  </form>
  <h4>Post Form</h4>
  <form action="/contact" method="post">
    <label for="member">Member</label>
    <%# input needs a type and a name %>
    <%# The name is the key in our params %>
    <input type="text" name="member" value='<%= params[:member] %>'>
    <%= hidden_field_tag :whatever, form_authenticity_token %>
    <button type='submit' class="btn btn-primary">Search</button>
  </form>
  <ul>
    <% @members.each do |member| %>
      <li><%= member.capitalize %></li>
    <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="container mt-5">
  <h1>Welcome</h1>
  <%# <a href="/about">About</a> %>
  <%= link_to 'About', about_path, class: 'btn btn-primary' %>
  <%= link_to 'Contact', contact_path, class: 'btn btn-primary' %>
</div>